-- Seed script for Product JWT project (PostgreSQL)
-- Creates dependent tables and inserts bulk sample data.
-- Includes encoded customer passwords in customer_auth using BCrypt via pgcrypto.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Recreate core tables to avoid legacy schema mismatches.
DROP TABLE IF EXISTS order_item CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS customer_auth CASCADE;
DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS customer CASCADE;

-- =========================
-- 1) Core tables
-- =========================

CREATE TABLE customer (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    address VARCHAR(500),
    phone VARCHAR(20)
);

CREATE TABLE product (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price NUMERIC(12, 2) NOT NULL CHECK (price > 0),
    category VARCHAR(50) NOT NULL CHECK (
        category IN (
            'ELECTRONICS',
            'CLOTHING',
            'BOOKS',
            'HOME_AND_KITCHEN',
            'SPORTS_AND_OUTDOORS',
            'TOYS_AND_GAMES',
            'BEAUTY_AND_PERSONAL_CARE',
            'GROCERIES',
            'OTHER'
        )
    ),
    brand VARCHAR(255),
    stocks INTEGER NOT NULL DEFAULT 0 CHECK (stocks >= 0)
);

CREATE TABLE orders (
    order_id BIGSERIAL PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES customer(id) ON DELETE CASCADE,
    order_date TIMESTAMP NOT NULL DEFAULT NOW(),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (
        status IN ('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED')
    )
);

CREATE TABLE order_item (
    id BIGSERIAL PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES product(id),
    quantity INTEGER NOT NULL CHECK (quantity > 0)
);

-- Separate auth table because current Customer entity does not include password column.
CREATE TABLE customer_auth (
    auth_id BIGSERIAL PRIMARY KEY,
    customer_id BIGINT NOT NULL UNIQUE REFERENCES customer(id) ON DELETE CASCADE,
    username VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL DEFAULT 'ROLE_USER' CHECK (role IN ('ROLE_USER', 'ROLE_ADMIN')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Helpful indexes
CREATE INDEX IF NOT EXISTS idx_orders_customer_id ON orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_order_item_order_id ON order_item(order_id);
CREATE INDEX IF NOT EXISTS idx_order_item_product_id ON order_item(product_id);
CREATE INDEX IF NOT EXISTS idx_product_category ON product(category);

-- =========================
-- 2) Seed Products (180)
-- =========================

INSERT INTO product (id, name, price, category, brand, stocks)
SELECT
    gs AS id,
    'Product ' || LPAD(gs::TEXT, 3, '0') AS name,
    ROUND((15 + ((gs * 7) % 950) + ((gs % 100) / 100.0))::NUMERIC, 2) AS price,
    (
        ARRAY[
            'ELECTRONICS',
            'CLOTHING',
            'BOOKS',
            'HOME_AND_KITCHEN',
            'SPORTS_AND_OUTDOORS',
            'TOYS_AND_GAMES',
            'BEAUTY_AND_PERSONAL_CARE',
            'GROCERIES',
            'OTHER'
        ]
    )[1 + (gs % 9)] AS category,
    (
        ARRAY['Acme', 'Nimbus', 'Zenith', 'Nova', 'Orion', 'Vertex', 'Pulse', 'Apex']
    )[1 + (gs % 8)] AS brand,
    25 + ((gs * 11) % 275) AS stocks
FROM generate_series(1, 180) AS gs;

-- =========================
-- 3) Seed Customers (60)
-- =========================

INSERT INTO customer (id, name, email, address, phone)
SELECT
    gs AS id,
    'Customer ' || LPAD(gs::TEXT, 3, '0') AS name,
    'customer' || LPAD(gs::TEXT, 3, '0') || '@example.com' AS email,
    (100 + gs) || ' Market Street, City-' || LPAD(((gs % 25) + 1)::TEXT, 2, '0') AS address,
    '90000' || LPAD(gs::TEXT, 5, '0') AS phone
FROM generate_series(1, 60) AS gs;

-- =========================
-- 4) Seed Auth Credentials
-- =========================
-- Plain password pattern: Cust@001 ... Cust@060
-- Stored hash: BCrypt (generated by pgcrypto crypt + gen_salt('bf', 10))

INSERT INTO customer_auth (auth_id, customer_id, username, password_hash, role)
SELECT
    c.id AS auth_id,
    c.id,
    'customer' || LPAD(c.id::TEXT, 3, '0') AS username,
    crypt('Cust@' || LPAD(c.id::TEXT, 3, '0'), gen_salt('bf', 10)) AS password_hash,
    CASE
        WHEN c.id IN (1, 2) THEN 'ROLE_ADMIN'
        ELSE 'ROLE_USER'
    END AS role
FROM customer c
ORDER BY c.id;

-- =========================
-- 5) Seed Orders (3 per customer => 180 orders)
-- =========================

INSERT INTO orders (order_id, customer_id, order_date, status)
SELECT
    ((c.id - 1) * 3 + ord.seq) AS order_id,
    c.id,
    NOW() - (((c.id * 4) + (ord.seq * 2)) || ' days')::INTERVAL,
    (
        ARRAY['PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED']
    )[1 + ((c.id + ord.seq) % 5)]
FROM customer c
CROSS JOIN generate_series(1, 3) AS ord(seq)
ORDER BY c.id, ord.seq;

-- =========================
-- 6) Seed Order Items (2-4 items per order)
-- =========================

INSERT INTO order_item (id, order_id, product_id, quantity)
SELECT
    ROW_NUMBER() OVER (ORDER BY o.order_id, item.seq) AS id,
    o.order_id,
    ((o.order_id * 17 + item.seq * 13) % 180) + 1 AS product_id,
    1 + ((o.order_id + item.seq) % 5) AS quantity
FROM orders o
CROSS JOIN LATERAL generate_series(1, 2 + (o.order_id % 3)) AS item(seq)
ORDER BY o.order_id, item.seq;

-- Keep sequences aligned for future inserts from the application.
SELECT setval('customer_id_seq', (SELECT COALESCE(MAX(id), 1) FROM customer), true);
SELECT setval('product_id_seq', (SELECT COALESCE(MAX(id), 1) FROM product), true);
SELECT setval('orders_order_id_seq', (SELECT COALESCE(MAX(order_id), 1) FROM orders), true);
SELECT setval('order_item_id_seq', (SELECT COALESCE(MAX(id), 1) FROM order_item), true);
SELECT setval('customer_auth_auth_id_seq', (SELECT COALESCE(MAX(auth_id), 1) FROM customer_auth), true);

COMMIT;

-- Optional verification queries:
-- SELECT COUNT(*) AS products FROM product;
-- SELECT COUNT(*) AS customers FROM customer;
-- SELECT COUNT(*) AS customer_auth_rows FROM customer_auth;
-- SELECT COUNT(*) AS orders FROM orders;
-- SELECT COUNT(*) AS order_items FROM order_item;
-- SELECT customer_id, COUNT(*) AS total_orders FROM orders GROUP BY customer_id ORDER BY customer_id;

